### ISSUE TITLE
Pytube is broken as of 12/22

### ISSUE THREAD

**Issue by achen88** [achen88/bootlegport#4]
bruh moment:
- https://github.com/nficano/pytube/issues/533
- major yt->mp3 websites are down
![image](https://user-images.githubusercontent.com/9738013/71340053-61dd1180-250a-11ea-853a-45dcfec11732.png)

**Comment by achen88** [comment]
looks like https://github.com/nficano/pytube/pull/534/files fixed it, but I'll wait for an official Pytube re-release instead of including the fix/Pytube source in this repo.

@forestyy

**Comment by boidushya** [comment]
> looks like https://github.com/nficano/pytube/pull/534/files fixed it, but I'll wait for an official Pytube re-release instead of including the fix/Pytube source in this repo.
> 
> @forestyy

It does work but for some copyrighted music, it still throws some errors.
@swiftyy-mage manages to fix it entirely
https://github.com/swiftyy-mage/pytube

**Comment by swiftyy-mage** [comment]
I had a stupid error because I forgot to import urllib, but I fixed that now. Should be working fine, enjoy!

**Comment by boidushya** [comment]
Great job man!

**Comment by hbmartin** [comment]
Hello, letting you know that there is a new, actively maintained, Python3 only pytube fork: https://github.com/hbmartin/pytube3

**Comment by achen88** [comment]
thanks @hbmartin. I was opposed to upgrading from the original pytube project but it appears as if pytube is not very actively maintained.

closed with 3fc8c99
